title: Corban Thompson
tagline: All about me
description: All about Corban Thompson
author: Corban Thompson
social:
  name: Corban Thompson
  links:
    - https://www.instagram.com/corban.thompson/
    - https://www.facebook.com/corban.thompson.1
    - https://github.com/corbant
    - https://www.linkedin.com/in/corban-thompson

domain: corbant.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://corbant.github.io # the base hostname and protocol for your site, e.g. http://example.com
baseurl: # place folder name if the site is served in a subfolder

plugins:
  - jekyll-seo-tag

exclude:
  [
    styles/index.css,
    styles/syntax.css,
    package.json,
    package-lock.json,
    postcss.config.js,
    readme.md,
    node_modules,
  ]
